name: Run pytest with Rye
# https://zenn.dev/link/comments/174f986fa82adb

on: [push]

jobs:
  setup:
    name: Install Rye and configure environment
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images/discussions/7188

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main

      - name: Install Dependencies
        run: rye sync

      - name: Lint
        run: rye run lint

      - name: Test
        run: rye run pytest
